version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: air-pollution-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    ports:
      - "5434:5432"  # 외부 포트 5434, 내부 포트 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: unless-stopped

  airflow-webserver:
    build: .
    command: webserver
    ports:
      - "9090:8080"
    depends_on:
      - postgres
    environment:
      TZ: Asia/Seoul
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Seoul
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY:-your_secret_key_here}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-ap-northeast-2}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME:-s3-airflow-toypjt-yh}
      OPENAPI_SERVICE_KEY: ${OPENAPI_SERVICE_KEY}
      OUTPUT_DIR: /opt/airflow/output
    volumes:
      - ./etl/dags:/opt/airflow/dags
      - ./etl/logs:/opt/airflow/logs
      - ./etl/output:/opt/airflow/output

  airflow-scheduler:
    build: .
    command: scheduler
    depends_on:
      - postgres
    environment:
      TZ: Asia/Seoul
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Seoul
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-ap-northeast-2}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME:-s3-airflow-toypjt-yh}
      OPENAPI_SERVICE_KEY: ${OPENAPI_SERVICE_KEY}
      OUTPUT_DIR: /opt/airflow/output
    volumes:
      - ./etl/dags:/opt/airflow/dags
      - ./etl/logs:/opt/airflow/logs
      - ./etl/output:/opt/airflow/output

volumes:
  postgres_db_volume:
