version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: air-pollution-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    ports:
      - "5434:5432"  # 외부 포트 5434, 내부 포트 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - etl_network

volumes:
  postgres_db_volume:

networks:
  etl_network:
    name: etl_network 